config/routes.rb
Rails.application.routes.draw do
  root to: "employees#index"
  resources :employees do
    member do
      get :history
      get :report
    end
  end
  resources :statuses
  resources :locations
  resources :time_works
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
class Employee < ApplicationRecord
  has_many :time_works

  validates :name, :last_name, :identification, presence: true
end

app/models/location.rb
class Location < ApplicationRecord
  has_many :time_works

  validates :name, presence: true
end

app/models/status.rb
class Status < ApplicationRecord
  has_many :time_works

  validates :name, presence: true
end

app/models/time_work.rb
class TimeWork < ApplicationRecord
  belongs_to :employee
  belongs_to :location
  belongs_to :status

  validates :start_date, :finish_date, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :find_employee, only: [:show, :destroy, :edit, :update, :history, :report]

  def index
    @employee = Employee.all
  end

  def new
    @employee = Employee.new
  end

  def create
    @employee = Employee.new(employee_params)
    if @employee.save
      redirect_to @employee, notice: "Empleado creado"
    else
      render :new
    end
  end

  def destroy
    if !@employee.time_works.present?
      if @employee.delete
        redirect_to employees_path
      else
        render employees_path
      end
    end
  end

  def edit
  end

  def update
    @employee.update(employee_params)
    if @employee.save
      redirect_to @employee
    else
      render :edit
    end
  end

  def history
  end

  def report
    render pdf: "report"
  end

  private

  def find_employee
    @employee = Employee.find(params[:id])
  end

  def employee_params
    params.require(:employee).permit(
      :name,
      :last_name,
      :identification
      )
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :find_location, only: [:show, :destroy, :edit, :update]

  def index
    @location = Location.all
  end

  def new
    @location = Location.new
  end

  def create
    @location = Location.new(location_params)
    if @location.save
      redirect_to @location, notice: "Ubicacion creada"
    else
      render :new
    end
  end

  def destroy
    if !@location.time_works.present?
      if @location.delete
        redirect_to locations_path
      else
        render locations_path
      end
    end
  end

  def edit
  end

  def update
    @location.update(location_params)
    if @location.save
      redirect_to @location
    else
      render :edit
    end
  end

  private

  def find_location
    @location = Location.find(params[:id])
  end

  def location_params
    params.require(:location).permit(
      :name
      )
  end
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :find_status, only: [:show, :destroy, :edit, :update]

  def index
    @status = Status.all
  end

  def new
    @status = Status.new
  end

  def create
    @status = Status.new(status_params)
    if @status.save
      redirect_to @status, notice: "Estado creado"
    else
      render :new
    end
  end

  def destroy
    if !@status.time_works.present?
      if @status.delete
        redirect_to statuses_path
      else
        render statuses_path
      end
    end
  end

  def edit
  end

  def update
    @status.update(status_params)
    if @status.save
      redirect_to @status
    else
      render :edit
    end
  end

  private

  def find_status
    @status = Status.find(params[:id])
  end

  def status_params
    params.require(:status).permit(
      :name
      )
  end
end

app/controllers/time_works_controller.rb
class TimeWorksController < ApplicationController
  before_action :find_time, only: [:show]

  def index
    @employee = Employee.all
  end

  def new
    @employee = Employee.all
    @location = Location.all
    @status = Status.all
    @time = TimeWork.new
  end

  def create
    @time = TimeWork.new(time_params)
    if @time.save
      redirect_to @time, notice: "creado"
    else
      @employee = Employee.all
      @location = Location.all
      @status = Status.all
      render :new
    end
  end

  def show
  end

  private

  def find_time
    @time = TimeWork.find(params[:id])
  end

  def time_params
    params.require(:time_work).permit(
      :status_id,
      :employee_id,
      :location_id,
      :finish_date,
      :start_date
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/employees/edit.html.erb
<%= form_for @employee do |employee| %>
  Nombre:
  <%= employee.text_field :name %></br>
  Apellido:
  <%= employee.text_field :last_name %></br>
  Cedula:
  <%= employee.text_field :identification %></br>
  <%= employee.submit "Modificar empleado" %>
<% end %>

app/views/employees/history.html.erb
<% if @employee.time_works.present? %>
  <%= @employee.time_works.each do |e| %>
    <div class="card col-md-6" style="">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">Nombre del empleado: <%=e.employee.name%></li>
        <li class="list-group-item">Ubicacion <%=e.location.name%></li>
        <li class="list-group-item">Fecha inicio: <%=e.start_date%></li>
        <li class="list-group-item">Fecha final: <%=e.finish_date%></li>
      </ul>
    </div>
  <% end %>
  <%=link_to "Crear PDF", report_employee_path, class: "btn btn-primary"%>
<% else %>
  <h1>No hay ubicacion para empleado todavia!!!</h1>
<% end %></br>

app/views/employees/index.html.erb
<% if @employee.present? %>
  <%= @employee.each do |e| %>
    <div class="card col-md-6" style="">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">Nombre del empleado: <%=e.name%></li>
        <li class="list-group-item">Apellido del empleado: <%=e.last_name%></li>
        <li class="list-group-item">Identificacion: <%=e.identification%></li>
      </ul>
      <div class="card-body">
        <%=link_to "Mostrar empleado", employee_path(e.id) %>
        <%=link_to "Modificar empleado", edit_employee_path(e.id) %>
        <%=link_to "Eliminar empleado",e, method: :delete %>
      </div>
    </div>
  <% end %>
<% else %>
  <h1>No hay empleados todavia!!!</h1>
<% end %></br>
<%=link_to "Agregar nuevo empleado", new_employee_path, class: "btn btn-primary"%>

app/views/employees/new.html.erb
<%= form_for @employee do |employee| %>
  Nombre:
  <%= employee.text_field :name %></br>
  Apellido:
  <%= employee.text_field :last_name %></br>
  Cedula:
  <%= employee.text_field :identification %></br>
  <%= employee.submit "Crear empleado" %>
<% end %>

app/views/employees/report.html.erb
<% if @employee.time_works.present? %>
  <%= @employee.time_works.each do |e| %>
    <div class="card col-md-6" style="">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">Nombre del empleado: <%=e.employee.name%></li>
        <li class="list-group-item">Ubicacion <%=e.location.name%></li>
        <li class="list-group-item">start_date: <%=e.start_date%></li>
        <li class="list-group-item">finish_date: <%=e.finish_date%></li>
      </ul>
    </div>
  <% end %>
<% else %>
  <h1>No hay ubicacion para empleado todavia!!!</h1>
<% end %></br>

app/views/employees/show.html.erb
<div class="card col-md-6" style="">
  <ul class="list-group list-group-flush">
    <li class="list-group-item">Nombre del empleado: <%=@employee.name%></li>
    <li class="list-group-item">Apellido del empleado: <%=@employee.last_name%></li>
    <li class="list-group-item">Identificacion: <%=@employee.identification%></li>
  </ul>
</div>
<%= link_to "Regresar a empleados", employees_path%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instacredit</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <nav class="navbar navbar-default" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand" <%=link_to "Mantenimiento empleados", employees_path %></a>
        </div>
        <a class="navbar-brand" <%=link_to "Mantenimiento ubicacion", locations_path %></a>
        <a class="navbar-brand" <%=link_to "Mantenimiento estado", statuses_path %></a>
        <a class="navbar-brand" <%=link_to "Ubicacion empleado", time_works_path %></a>
      </div>
    </nav>

    <p class="notice text-success text-center text-uppercase">
    <%= notice %>
    <p class="alert text-danger text-center text-uppercase">
    <%= alert %>
  </p>
</p>
  </head>

  <body class="container">
    <%= yield %>
  </body>
</html>

app/views/locations/edit.html.erb
<%= form_for @location do |location| %>
  <p>Centro:</p>
  <%= location.text_field :name %></br>
  <%= location.submit "Modificar ubicacion" %>
<% end %>

app/views/locations/index.html.erb
<% if @location.present? %>
  <%= @location.each do |l| %>
    <div class="card col-md-6" style="">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">Codigo de centro: <%=l.id%></li>
        <li class="list-group-item">Nombre de centro: <%=l.name%></li>
      </ul>
      <div class="card-body">
        <%=link_to "Mostrar ubicacion", location_path(l.id) %>
        <%=link_to "Modificar ubicacion", edit_location_path(l.id) %>
        <%=link_to "Eliminar ubicacion",l, method: :delete %>
      </div>
    </div>
  <% end %>
<% else %>
  <h1>No hay ubicaciones todavia!!!</h1>
<% end %>
<%=link_to "Agregar nueva ubicacion", new_location_path, class:"btn btn-primary" %>

app/views/locations/new.html.erb
<%= form_for @location do |location| %>
  <p>Centro:</p>
  <%= location.text_field :name %></br>
  <%= location.submit "Crear ubicacion" %>
<% end %>

app/views/locations/show.html.erb
<div class="card col-md-6" style="">
  <ul class="list-group list-group-flush">
    <li class="list-group-item">Codigo centro: <%=@location.id%></li>
    <li class="list-group-item">Centro: <%= @location.name%></li>
  </ul>
</div>
<%= link_to "Regresar a ubicaciones", locations_path%>

app/views/statuses/edit.html.erb
<%= form_for @status do |status| %>
  Estado:
  <%= status.text_field :name %></br>
  <%= status.submit "Modificar estado"%>
<% end %>

app/views/statuses/index.html.erb
<% if @status.present? %>
  <%= @status.each do |s| %>
  <div class="card col-md-6" style="">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">Codigo de ubicacion: <%=s.id%></li>
      <li class="list-group-item">Nombre de la ubicacion: <%=s.name%></li>
    </ul>
    <div class="card-body">
      <%=link_to "Mostrar estado", status_path(s.id) %>
      <%=link_to "Modificar estado", edit_status_path(s.id) %>
      <%=link_to "Eliminar estado",s, method: :delete %>
    </div>
  </div>


  <% end %>
<% else %>
  <h1>No hay estados todavia!!!</h1>
<% end %>
<%=link_to "Agregar nuevo estado", new_status_path, class: "btn btn-primary" %>

app/views/statuses/new.html.erb
<%= form_for @status do |status| %>
  Estado:
  <%= status.text_field :name %></br>
  <%= status.submit "Crear estado"%>
<% end %>

app/views/statuses/show.html.erb
<div class="card col-md-6" style="">
  <ul class="list-group list-group-flush">
    <li class="list-group-item">Codigo estado: <%= @status.id%></li>
    <li class="list-group-item">Estado: <%= @status.name%></li>
  </ul>
</div>
<%= link_to "Regresar a estados", statuses_path%>

app/views/time_works/index.html.erb
<% if @employee.present? %>
  <%= @employee.each do |e| %>
    <div class="card col-md-6" style="">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">Nombre del empleado: <%=e.name%></li>
        <li class="list-group-item">Apellido del empleado: <%=e.last_name%></li>
        <li class="list-group-item">Identificacion: <%=e.identification%></li>
      </ul>
      <div class="card-body">
        <%=link_to "Historico de ubicaciones", history_employee_path(e.id) %>
      </div>
    </div>
  <% end %>
<% else %>
  <h1>No hay empleados todavia!!!</h1>
<% end %>
<%=link_to "Agregar empleado ubicacion", new_time_work_path, class: "btn btn-primary"%>

app/views/time_works/new.html.erb
<%= form_for @time do |time| %>
  Fecha de inicio:
  <%= time.date_field :start_date %></br>
  Fecha final:
  <%= time.date_field :finish_date %></br>
  Empleado:
  <%= time.select :employee_id, @employee.pluck(:name, :id)%><br>
  Estado:
  <%= time.select :status_id, @status.pluck(:name, :id)%><br>
  Ubicacion:
  <%= time.select :location_id, @location.pluck(:name, :id)%><br>
  <%= time.submit "Agregar"%>
<% end %>

app/views/time_works/show.html.erb
<div class="card col-md-6" style="">
  <ul class="list-group list-group-flush">
    <li class="list-group-item">Nombre del empleado: <%=@time.employee.name%></li>
    <li class="list-group-item">Ubicacion: <%=@time.location.name%></li>
    <li class="list-group-item">Estado: <%=@time.status.name%></li>
    <li class="list-group-item">Fecha inicio: <%=@time.start_date%></li>
    <li class="list-group-item">Fecha final: <%=@time.finish_date%></li>
  </ul>
</div>
<%= link_to "Regresar", time_works_path%>